"""Updates for JobApplication

Revision ID: 07be49b4c9ce
Revises: ee13f41d6e62
Create Date: 2025-10-21 23:22:45.173466

"""
from alembic import op
import sqlalchemy as sa
import resume_builder


# revision identifiers, used by Alembic.
revision = '07be49b4c9ce'
down_revision = 'ee13f41d6e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_application',
    sa.Column('id', resume_builder.models.GUID(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('job_url', sa.String(), nullable=True),
    sa.Column('application_source', sa.String(), nullable=False),
    sa.Column('application_stage_id', sa.Integer(), nullable=False),
    sa.Column('user_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_stage_id'], ['application_stage.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('built_resume', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_built_resume_theme_id'), type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'basic_info', ['basic_info_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'summary', ['summary_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'resume_theme', ['theme_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('built_resume_education', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'education', ['education_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'built_resume', ['built_resume_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('built_resume_experience', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'built_resume', ['built_resume_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'experience', ['experience_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('built_resume_language', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'language', ['language_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'built_resume', ['built_resume_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('built_resume_skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'skills', ['skills_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'built_resume', ['built_resume_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.create_unique_constraint('_invitecode_user_id_uc', ['user_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('resume_theme', schema=None) as batch_op:
        batch_op.create_unique_constraint('_resumetheme_name_uc', ['name'])

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_username_uc', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('_user_username_uc', type_='unique')

    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('resume_theme', schema=None) as batch_op:
        batch_op.drop_constraint('_resumetheme_name_uc', type_='unique')

    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('invite_code', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_constraint('_invitecode_user_id_uc', type_='unique')

    with op.batch_alter_table('experience', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('built_resume_skills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'built_resume', ['built_resume_id'], ['id'])
        batch_op.create_foreign_key(None, 'skills', ['skills_id'], ['id'])

    with op.batch_alter_table('built_resume_language', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'built_resume', ['built_resume_id'], ['id'])
        batch_op.create_foreign_key(None, 'language', ['language_id'], ['id'])

    with op.batch_alter_table('built_resume_experience', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'built_resume', ['built_resume_id'], ['id'])
        batch_op.create_foreign_key(None, 'experience', ['experience_id'], ['id'])

    with op.batch_alter_table('built_resume_education', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'built_resume', ['built_resume_id'], ['id'])
        batch_op.create_foreign_key(None, 'education', ['education_id'], ['id'])

    with op.batch_alter_table('built_resume', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'summary', ['summary_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_built_resume_theme_id'), 'resume_theme', ['theme_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'basic_info', ['basic_info_id'], ['id'])

    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    op.drop_table('job_application')
    op.drop_table('application_stage')
    # ### end Alembic commands ###
