"""Added BasicInfo and Summary resume sections as models

Revision ID: 21e0e57ad81f
Revises: 4cdaad2e8e4e
Create Date: 2025-09-25 07:33:27.853795

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21e0e57ad81f"
down_revision = "4cdaad2e8e4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "basic_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=50), nullable=True),
        sa.Column("job_title", sa.String(length=50), nullable=True),
        sa.Column("address", sa.String(length=50), nullable=True),
        sa.Column("contact_email", sa.String(length=30), nullable=True),
        sa.Column("contact_phone", sa.String(length=30), nullable=True),
        sa.Column("linkedin_url", sa.String(length=100), nullable=True),
        sa.Column("github_url", sa.String(length=100), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("summary_name", sa.String(length=50), nullable=False),
        sa.Column("summary_content", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("summary")
    op.drop_table("basic_info")
    # ### end Alembic commands ###
