"""Create InviteCode model

Revision ID: 3feed69f8206
Revises: bc7b152acc96
Create Date: 2025-10-13 02:05:48.594544

"""

from alembic import op
import sqlalchemy as sa
import resume_builder


# revision identifiers, used by Alembic.
revision = "3feed69f8206"
down_revision = "bc7b152acc96"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invite_code",
        sa.Column("id", resume_builder.models.GUID(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("redeemed", sa.Boolean(), nullable=False),
        sa.Column("user_id", resume_builder.models.GUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("invite_code")
    # ### end Alembic commands ###
