"""Added typical timestamps

Revision ID: 4187f502c164
Revises: 21e0e57ad81f
Create Date: 2025-09-26 18:21:17.378699

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision = '4187f502c164'
down_revision = '21e0e57ad81f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=str(datetime.now(timezone.utc))))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=str(datetime.now(timezone.utc))))

    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=str(datetime.now(timezone.utc))))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=str(datetime.now(timezone.utc))))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, server_default=str(datetime.now(timezone.utc))))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=str(datetime.now(timezone.utc))))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
