"""Created Eductaion model

Revision ID: 7023bbedcd75
Revises: a34c4e2939f3
Create Date: 2025-09-29 03:49:43.630023

"""
from alembic import op
import sqlalchemy as sa
import resume_builder


# revision identifiers, used by Alembic.
revision = '7023bbedcd75'
down_revision = 'a34c4e2939f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', resume_builder.models.GUID(), nullable=False),
    sa.Column('degree_name', sa.String(length=50), nullable=False),
    sa.Column('school_name', sa.String(length=50), nullable=False),
    sa.Column('date_started', sa.Date(), nullable=False),
    sa.Column('date_finished', sa.Date(), nullable=True),
    sa.Column('user_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('entry_title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_title', name='_user_experience_title_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('education')
    # ### end Alembic commands ###
