"""Initial migration to create all models.

Revision ID: 7de7970f4d8b
Revises: 
Create Date: 2025-10-01 10:40:36.273371

"""
from alembic import op
import sqlalchemy as sa
import resume_builder


# revision identifiers, used by Alembic.
revision = '7de7970f4d8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', resume_builder.models.GUID(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('basic_info',
    sa.Column('id', resume_builder.models.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('contact_email', sa.String(length=30), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('linkedin_url', sa.String(length=100), nullable=True),
    sa.Column('github_url', sa.String(length=100), nullable=True),
    sa.Column('user_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('entry_title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_title', name='_user_entry_title_uc')
    )
    op.create_table('education',
    sa.Column('id', resume_builder.models.GUID(), nullable=False),
    sa.Column('degree_name', sa.String(length=50), nullable=False),
    sa.Column('school_name', sa.String(length=50), nullable=False),
    sa.Column('date_started', sa.Date(), nullable=False),
    sa.Column('date_finished', sa.Date(), nullable=True),
    sa.Column('user_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('entry_title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_title', name='_user_education_title_uc')
    )
    op.create_table('experience',
    sa.Column('id', resume_builder.models.GUID(), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=False),
    sa.Column('date_started', sa.Date(), nullable=False),
    sa.Column('date_finished', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('entry_title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_title', name='_user_experience_title_uc')
    )
    op.create_table('language',
    sa.Column('id', resume_builder.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('proficiency', sa.String(length=30), nullable=False),
    sa.Column('user_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('entry_title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_title', name='_user_language_title_uc')
    )
    op.create_table('skills',
    sa.Column('id', resume_builder.models.GUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('entry_title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_title', name='_user_skills_title_uc')
    )
    op.create_table('summary',
    sa.Column('id', resume_builder.models.GUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('user_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('entry_title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_title', name='_user_summary_title_uc')
    )
    op.create_table('built_resume',
    sa.Column('id', resume_builder.models.GUID(), nullable=False),
    sa.Column('basic_info_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('summary_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('user_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('entry_title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['basic_info_id'], ['basic_info.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_title', name='_user_built_resumes_title_uc')
    )
    op.create_table('built_resume_education',
    sa.Column('built_resume_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('education_id', resume_builder.models.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['built_resume_id'], ['built_resume.id'], ),
    sa.ForeignKeyConstraint(['education_id'], ['education.id'], ),
    sa.PrimaryKeyConstraint('built_resume_id', 'education_id')
    )
    op.create_table('built_resume_experience',
    sa.Column('built_resume_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('experience_id', resume_builder.models.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['built_resume_id'], ['built_resume.id'], ),
    sa.ForeignKeyConstraint(['experience_id'], ['experience.id'], ),
    sa.PrimaryKeyConstraint('built_resume_id', 'experience_id')
    )
    op.create_table('built_resume_language',
    sa.Column('built_resume_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('language_id', resume_builder.models.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['built_resume_id'], ['built_resume.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('built_resume_id', 'language_id')
    )
    op.create_table('built_resume_skills',
    sa.Column('built_resume_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('skills_id', resume_builder.models.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['built_resume_id'], ['built_resume.id'], ),
    sa.ForeignKeyConstraint(['skills_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('built_resume_id', 'skills_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('built_resume_skills')
    op.drop_table('built_resume_language')
    op.drop_table('built_resume_experience')
    op.drop_table('built_resume_education')
    op.drop_table('built_resume')
    op.drop_table('summary')
    op.drop_table('skills')
    op.drop_table('language')
    op.drop_table('experience')
    op.drop_table('education')
    op.drop_table('basic_info')
    op.drop_table('user')
    # ### end Alembic commands ###
