"""Add Experience table

Revision ID: a34c4e2939f3
Revises: 4187f502c164
Create Date: 2025-09-27 05:42:19.854751

"""
from alembic import op
import sqlalchemy as sa
import resume_builder


# revision identifiers, used by Alembic.
revision = 'a34c4e2939f3'
down_revision = '4187f502c164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience',
    sa.Column('id', resume_builder.models.GUID(), nullable=False),
    sa.Column('job_title', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=50), nullable=False),
    sa.Column('date_started', sa.Date(), nullable=False),
    sa.Column('date_finished', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('entry_title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_title', name='_user_experience_title_uc')
    )
    op.drop_table('_alembic_tmp_basic_info')
    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_title', sa.String(length=50), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=resume_builder.models.GUID(),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('job_title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('contact_email',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('contact_phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=resume_builder.models.GUID(),
               existing_nullable=False)
        batch_op.create_unique_constraint('_user_entry_title_uc', ['user_id', 'entry_title'])

    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('entry_title', sa.String(length=50), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=resume_builder.models.GUID(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=resume_builder.models.GUID(),
               existing_nullable=False)
        batch_op.create_unique_constraint('_user_summary_title_uc', ['user_id', 'entry_title'])
        batch_op.drop_column('summary_content')
        batch_op.drop_column('summary_name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=resume_builder.models.GUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=resume_builder.models.GUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_name', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('summary_content', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('_user_summary_title_uc', type_='unique')
        batch_op.alter_column('user_id',
               existing_type=resume_builder.models.GUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=resume_builder.models.GUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('entry_title')
        batch_op.drop_column('content')

    with op.batch_alter_table('basic_info', schema=None) as batch_op:
        batch_op.drop_constraint('_user_entry_title_uc', type_='unique')
        batch_op.alter_column('user_id',
               existing_type=resume_builder.models.GUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('contact_phone',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('contact_email',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('job_title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=resume_builder.models.GUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('entry_title')

    op.create_table('_alembic_tmp_basic_info',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('address', sa.VARCHAR(length=50), nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=30), nullable=False),
    sa.Column('contact_phone', sa.VARCHAR(length=30), nullable=False),
    sa.Column('linkedin_url', sa.VARCHAR(length=100), nullable=True),
    sa.Column('github_url', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text("'2025-09-27 03:37:29.959565+00:00'"), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text("'2025-09-27 03:37:29.959937+00:00'"), nullable=False),
    sa.Column('entry_title', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_title', name=op.f('_user_entry_title_uc'))
    )
    op.drop_table('experience')
    # ### end Alembic commands ###
