"""add Skills model

Revision ID: ac28ba606033
Revises: 7023bbedcd75
Create Date: 2025-09-29 07:09:30.927063

"""

from alembic import op
import sqlalchemy as sa
import resume_builder


# revision identifiers, used by Alembic.
revision = "ac28ba606033"
down_revision = "7023bbedcd75"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("id", resume_builder.models.GUID(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("user_id", resume_builder.models.GUID(), nullable=False),
        sa.Column("entry_title", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "entry_title", name="_user_experience_title_uc"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skills")
    # ### end Alembic commands ###
