"""Create theme model

Revision ID: cd4ec0192cab
Revises: 7de7970f4d8b
Create Date: 2025-10-02 07:32:58.817807

"""

from alembic import op
import sqlalchemy as sa
import resume_builder


# revision identifiers, used by Alembic.
revision = "cd4ec0192cab"
down_revision = "7de7970f4d8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resume_theme",
        sa.Column("id", resume_builder.models.GUID(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("styles", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resume_theme")
    # ### end Alembic commands ###
