"""Created Resume builder and relationships

Revision ID: e9a266987aa9
Revises: 320c318afcd9
Create Date: 2025-09-30 06:00:10.957478

"""
from alembic import op
import sqlalchemy as sa
import resume_builder

# revision identifiers, used by Alembic.
revision = 'e9a266987aa9'
down_revision = '320c318afcd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('built_resume',
    sa.Column('id', resume_builder.models.GUID(), nullable=False),
    sa.Column('basic_info_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('summary_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('user_id', resume_builder.models.GUID(), nullable=False),
    sa.Column('entry_title', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['basic_info_id'], ['basic_info.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['summary.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entry_title', name='_user_experience_title_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('built_resume')
    # ### end Alembic commands ###
