"""Built Resume and Theme relationship

Revision ID: fbc716718bf2
Revises: cd4ec0192cab
Create Date: 2025-10-02 08:14:12.830622

"""

from alembic import op
import sqlalchemy as sa
import resume_builder


# revision identifiers, used by Alembic.
revision = "fbc716718bf2"
down_revision = "cd4ec0192cab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("built_resume", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("theme_id", resume_builder.models.GUID(), nullable=False)
        )
        batch_op.create_foreign_key(
            "fk_built_resume_theme_id", "resume_theme", ["theme_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("built_resume", schema=None) as batch_op:
        batch_op.drop_constraint("fk_built_resume_theme_id", type_="foreignkey")
        batch_op.drop_column("theme_id")

    # ### end Alembic commands ###
